[package]
name = "rushell"
version = "0.1.0"
authors = ["MorenoAlexander <am@alexandermoreno.com>"]
edition = "2021"
target = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-error = "0.2"
ctrlc = "3.2.5"